name: Build Fedora LiveCD ISO
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ISO with Docker
        run: |
          docker run --privileged --rm -v ${{ github.workspace }}:/build fedora:38 bash -c "mount --make-rprivate / && sed -i '/exclude/d' /etc/dnf/dnf.conf && sed -i '/exclude/d' /etc/yum.repos.d/*.repo && dnf install -y livecd-tools util-linux && echo 'install_weak_deps=False' >> /etc/dnf/dnf.conf && echo 'tsflags=noscripts' >> /etc/dnf/dnf.conf && echo '%_install_langs C' > /etc/rpm/macros.langs && sed -i 's/raise MountError(umount_fail_fmt.*/pass/g' /usr/lib/python3.*/site-packages/imgcreate/fs.py && cd /build && livecd-creator --verbose --config=fedora-live-tecnico.ks --fslabel=ISO_LOUCA_BOOT"

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ISO-LOUCA-BOOT
          path: ISO_LOUCA_BOOT.iso
