name: Build Fedora LiveCD ISO
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ISO with Docker
        run: |
          docker run --privileged --rm -v ${{ github.workspace }}:/build fedora:latest bash -c "dnf install -y livecd-tools spin-kickstarts && cd /build && livecd-creator --verbose --config=fedora-live-tecnico.ks --fslabel=ISO_LOUCA_BOOT"

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ISO-LOUCA-BOOT
          path: ISO_LOUCA_BOOT.iso
